import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9fa",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c6cc",
        "tertiary-container": "#1c1c11",
        "tertiary-fixed": "#e6e3d0",
        "on-primary": "#ffffff",
        "on-surface-variant": "#44474c",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#3c475d",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1c1c11",
        "primary-container": "#3c0800",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed": "#d7e2ff",
        "surface-container-high": "#e7e8e9",
        "tertiary-fixed-dim": "#c9c7b5",
        "on-primary-container": "#c9684e",
        "inverse-surface": "#2e3132",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed-variant": "#7c2e19",
        "secondary-container": "#d7e2ff",
        "on-primary-fixed": "#3c0800",
        "surface-tint": "#9a442d",
        "primary-fixed-dim": "#ffb4a1",
        "on-secondary-container": "#5a647c",
        "on-surface": "#191c1d",
        "primary": "#000000",
        "inverse-primary": "#ffb4a1",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#48473a",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#bbc6e2",
        "primary-fixed": "#ffdbd2",
        "secondary": "#545e76",
        "on-secondary-fixed": "#101b30",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-low": "#f3f4f5",
        "outline": "#74777d",
        "on-error-container": "#93000a",
        "tertiary": "#000000",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "on-tertiary-container": "#868474",
        "surface-container-highest": "#e1e3e4",
        
        // EvalTrack Prompt Colors (blended as requested)
        "navy": '#1A1A2E',
        "terra": { DEFAULT: '#E8623A', light: '#F4A07A', dark: '#C44E28' },
        "forest": '#2D6A4F',
        "cream": '#F8F7F4',
        "danger": '#DC2626',
        "warning": '#D97706',
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "xl2": "1rem",
        "xl3": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Manrope", "Playfair Display", "serif"],
        body: ["Inter", "DM Sans", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: ['Playfair Display', 'serif'],
        sans: ['DM Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04)',
        modal: '0 8px 32px rgba(0,0,0,0.12)',
        terra: '0 4px 14px rgba(232,98,58,0.25)',
        ambient: '0 20px 40px rgba(0, 0, 0, 0.06)'
      }
    },
  },
  plugins: [],
} satisfies Config
